included:
  - Picklet
  - PickletTests
  - PickletUITests

excluded:
  - Pods
  - Carthage
  - vendor
  - DerivedData
  - fastlane
  - Picklet/Preview Content

# デフォルトルールの中で無効化するもの
disabled_rules:
  - todo
  - trailing_whitespace # 必要に応じて有効化
  - indentation_width
  - for_where

# オプショナルルールの中で有効化するもの
opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - first_where
  - sorted_imports
  - object_literal
  - number_separator

# カスタム値
line_length:
  warning: 120
  error: 150
  ignores_comments: true

file_length:
  warning: 400
  error: 500

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 350
  error: 500

large_tuple:
  warning: 3
  error: 4

# 変数名の長さ
identifier_name:
  min_length: 2
  excluded:
    - id
    - up
    - x
    - y
    - z
    - i
    - j
    - n

reporter: "xcode"
