name: Build and Test

on:
  push:
    branches-ignore:
      - 'gh-pages'
      - 'docs/**'
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository with token
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0
          token: ${{ github.token }}  # 明示的にトークンを指定

      # xcprettyがインストールされているか確認し、PATHに追加
      - name: Set up Ruby environment
        run: |
          echo "Setting up Ruby environment..."
          export GEM_HOME="$HOME/.gem/ruby/$(ruby -e 'puts RUBY_VERSION.match(/\d+\.\d+/)[0]')"
          export PATH="$GEM_HOME/bin:$PATH"
          echo "Ruby version: $(ruby --version)"
          echo "Gem path: $GEM_HOME"
          echo "PATH: $PATH"
          echo "GEM_HOME=$GEM_HOME" >> $GITHUB_ENV
          echo "$GEM_HOME/bin" >> $GITHUB_PATH

      - name: Install xcpretty if needed
        run: |
          gem environment
          if ! command -v xcpretty &> /dev/null; then
            echo "Installing xcpretty..."
            gem install --user-install xcpretty
          fi
          echo "xcpretty path: $(which xcpretty || echo 'Not found')"
          echo "xcpretty version: $(xcpretty --version || echo 'Failed to get version')"

      - name: Pull LFS files
        run: |
          git lfs install
          git lfs pull

      # モデルファイルの健全性を検証
      - name: Verify LFS file integrity
        run: |
          echo "Checking ISNet.mlmodel file size and type:"
          du -h Picklet/Models/ISNet.mlmodel
          file Picklet/Models/ISNet.mlmodel

          # ファイルが小さすぎる場合はエラーを表示
          FILE_SIZE=$(du -k Picklet/Models/ISNet.mlmodel | cut -f1)
          if [ $FILE_SIZE -lt 10000 ]; then
            echo "::error::ISNet.mlmodel is too small ($FILE_SIZE KB), likely not properly fetched from LFS"
            echo "File contents:"
            head -n 20 Picklet/Models/ISNet.mlmodel
            exit 1
          else
            echo "✅ ISNet.mlmodel size looks good: $FILE_SIZE KB"
          fi

      - name: Dump MLModel header
        run: |
          echo "First 16 bytes of ISNet.mlmodel:"
          head -c 16 Picklet/Models/ISNet.mlmodel | xxd

      # Swift Packageのダウンロードを別ステップとして分離し、出力を最小限に
      - name: Resolve Swift Packages
        run: |
          xcodebuild -resolvePackageDependencies -project Picklet.xcodeproj -scheme Picklet | grep -v "^$" | grep -v "Creating working copy" | grep -v "Fetching from" | grep -v "Checking out"

      - name: Clean
        run: |
          xcodebuild clean -project Picklet.xcodeproj -scheme Picklet -quiet

      - name: List available simulators
        run: |
          xcrun simctl list devices available | grep -E 'iPhone|iPad'

      - name: Build
        run: |
          # xcprettyを使わない構成に変更
          xcodebuild build -project Picklet.xcodeproj -scheme Picklet -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.3.1' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO COMPILER_INDEX_STORE_ENABLE=NO -quiet

      # テストが必要な場合のみ実行
      - name: Test
        if: github.event_name == 'pull_request' || contains(github.ref, 'main')
        run: |
          # xcprettyを使わない構成に変更
          xcodebuild test -project Picklet.xcodeproj -scheme Picklet -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.3.1' -skip-testing:PickletUITests COMPILER_INDEX_STORE_ENABLE=NO -quiet
