name: Build and Test

on:
  push:
    branches-ignore:
      - 'gh-pages'
      - 'docs/**'
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        lfs: true  # LFSファイルを明示的に取得
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Verify LFS files
      run: |
        # LFSファイルが正しく取得できているか確認
        echo "Checking ISNet.mlmodel file size:"
        du -h Picklet/Models/ISNet.mlmodel
    
    # Swift Packageのダウンロードを別ステップとして分離し、出力を最小限に
    - name: Resolve Swift Packages
      run: |
        xcodebuild -resolvePackageDependencies -project Picklet.xcodeproj -scheme Picklet | grep -v "^$" | grep -v "Creating working copy" | grep -v "Fetching from" | grep -v "Checking out"
    
    - name: Clean
      run: |
        xcodebuild clean -project Picklet.xcodeproj -scheme Picklet -quiet
    
    - name: Build
      run: |
        # ログ出力を最小限にする
        set -o pipefail && xcodebuild build -project Picklet.xcodeproj -scheme Picklet -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -quiet | xcpretty -c --simple --no-utf

    # テストが必要な場合のみ実行
    - name: Test
      if: github.event_name == 'pull_request' || contains(github.ref, 'main')
      run: |
        # テストのみ実行、ログ出力を最小限にする
        set -o pipefail && xcodebuild test -project Picklet.xcodeproj -scheme Picklet -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' -skip-testing:PickletUITests -quiet | xcpretty -c --test --no-utf