name: Build and Test

on:
  push:
    branches: [ main, 79-loadimage ]  # 現在のブランチも対象に追加
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        lfs: true  # LFSファイルを明示的に取得
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: List LFS files (verify checkout)
      run: |
        # LFSファイルが正しく取得できているか確認
        echo "Checking ISNet.mlmodel file size:"
        du -h Picklet/Models/ISNet.mlmodel
        echo "Making sure LFS files are properly fetched"
    
    - name: Build and Test
      run: |
        # 利用可能なシミュレーター一覧を表示
        xcrun simctl list devices
        
        # iPhone 16を使用（利用可能なシミュレーターに基づいて選択）
        xcodebuild -project Picklet.xcodeproj -scheme Picklet -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.2' build test