name: Swift Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Build and Test
      run: |
        xcodebuild test -project Picklet.xcodeproj -scheme Picklet -destination 'platform=iOS Simulator,name=iPhone 15' | xcpretty

  test-linux:
    # Ubuntu 24.04がサポートされていないため22.04を明示的に指定
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: "5.9"
    - name: Create Package.swift
      run: |
        echo '// swift-tools-version:5.9' > Package.swift
        echo 'import PackageDescription' >> Package.swift
        echo '' >> Package.swift
        echo 'let package = Package(' >> Package.swift
        echo '    name: "Picklet",' >> Package.swift
        echo '    platforms: [.iOS(.v16)],' >> Package.swift
        echo '    products: [' >> Package.swift
        echo '        .library(name: "PickletCore", targets: ["PickletCore"]),' >> Package.swift
        echo '    ],' >> Package.swift
        echo '    dependencies: [],' >> Package.swift
        echo '    targets: [' >> Package.swift
        echo '        .target(' >> Package.swift
        echo '            name: "PickletCore",' >> Package.swift
        echo '            dependencies: [],' >> Package.swift
        echo '            path: "Picklet",' >> Package.swift
        echo '            exclude: ["Views", "Extensions", "PickletApp.swift", "Resources", "Preview Content"],' >> Package.swift
        echo '            sources: ["Models", "Services"]' >> Package.swift
        echo '        ),' >> Package.swift
        echo '        .testTarget(' >> Package.swift
        echo '            name: "PickletCoreTests",' >> Package.swift
        echo '            dependencies: ["PickletCore"],' >> Package.swift
        echo '            path: "PickletTests",' >> Package.swift
        echo '            exclude: ["PickletUITests.swift"]' >> Package.swift
        echo '        )' >> Package.swift
        echo '    ]' >> Package.swift
        echo ')' >> Package.swift
    - name: Run Linux-compatible tests
      run: |
        # 明示的にLinux対応のテストのみを実行
        swift test --filter "PickletTests.testClothingModel" --filter "PickletTests.testWeatherModel"